import { ITodos } from '../type/todo'

export const dummytodos: ITodos[] = [
    {
        key: '1',
        title: 'Complete project report',
        description: 'Finish the report and send it to the manager.',
        status: 'todo',
        category: 'work',
        priority: 'high',
        createdAt: '2024-12-01T09:00:00Z',
        dueDate: '2024-12-05T17:00:00Z',
    },
    {
        key: '2',
        title: 'Grocery shopping',
        description: 'Buy vegetables, fruits, and dairy products.',
        status: 'completed',
        category: 'personal',
        priority: 'medium',
        createdAt: '2024-11-30T10:00:00Z',
        dueDate: '2024-11-30T15:00:00Z',
    },
    {
        key: '3',
        title: 'Clean the house',
        description: 'Vacuum, dust, and mop the floors.',
        status: 'todo',
        category: 'home',
        priority: 'low',
        createdAt: '2024-12-01T08:30:00Z',
        dueDate: '2024-12-03T18:00:00Z',
    },
    {
        key: '4',
        title: 'Team meeting preparation',
        description: 'Prepare slides and agenda for the meeting.',
        status: 'todo',
        category: 'work',
        priority: 'high',
        createdAt: '2024-12-01T07:00:00Z',
        dueDate: '2024-12-02T10:00:00Z',
    },
    {
        key: '5',
        title: 'Exercise session',
        description: 'Morning run and strength training.',
        status: 'completed',
        category: 'personal',
        priority: 'medium',
        createdAt: '2024-11-28T06:00:00Z',
        dueDate: '2024-11-28T07:00:00Z',
    },
    {
        key: '6',
        title: 'Fix kitchen sink',
        description: 'Call the plumber for sink repair.',
        status: 'todo',
        category: 'home',
        priority: 'medium',
        createdAt: '2024-12-01T11:00:00Z',
        dueDate: '2024-12-04T16:00:00Z',
    },
    {
        key: '7',
        title: 'Book dentist appointment',
        description: 'Schedule a check-up for next week.',
        status: 'todo',
        category: 'personal',
        priority: 'low',
        createdAt: '2024-11-29T12:00:00Z',
        dueDate: '2024-12-03T09:00:00Z',
    },
    {
        key: '8',
        title: 'Update software',
        description: 'Ensure all work tools are up to date.',
        status: 'completed',
        category: 'work',
        priority: 'medium',
        createdAt: '2024-11-27T14:00:00Z',
        dueDate: '2024-11-27T17:00:00Z',
    },
    {
        key: '9',
        title: 'Organize bookshelf',
        description: 'Sort and arrange books by genre.',
        status: 'todo',
        category: 'home',
        priority: 'low',
        createdAt: '2024-12-01T14:00:00Z',
        dueDate: '2024-12-06T18:00:00Z',
    },
    {
        key: '10',
        title: 'Family dinner',
        description: 'Plan and cook a special dinner for family.',
        status: 'todo',
        category: 'personal',
        priority: 'high',
        createdAt: '2024-12-01T15:30:00Z',
        dueDate: '2024-12-01T20:00:00Z',
    },
    {
        key: '11',
        title: 'Submit tax documents',
        description: 'Gather and submit all necessary forms.',
        status: 'completed',
        category: 'work',
        priority: 'high',
        createdAt: '2024-11-25T08:00:00Z',
        dueDate: '2024-11-30T23:59:00Z',
    },
    {
        key: '12',
        title: 'Laundry day',
        description: 'Wash and fold clothes.',
        status: 'todo',
        category: 'home',
        priority: 'medium',
        createdAt: '2024-12-02T09:00:00Z',
        dueDate: '2024-12-02T18:00:00Z',
    },
    {
        key: '13',
        title: 'Plan weekend trip',
        description: 'Choose destination and book accommodation.',
        status: 'todo',
        category: 'personal',
        priority: 'medium',
        createdAt: '2024-12-01T13:00:00Z',
        dueDate: '2024-12-04T12:00:00Z',
    },
    {
        key: '14',
        title: 'Monthly budget review',
        description: 'Analyze spending and adjust budget for next month.',
        status: 'completed',
        category: 'personal',
        priority: 'high',
        createdAt: '2024-11-30T18:00:00Z',
        dueDate: '2024-11-30T20:00:00Z',
    },
    {
        key: '15',
        title: 'Fix broken chair',
        description: 'Repair or replace the broken leg.',
        status: 'todo',
        category: 'home',
        priority: 'low',
        createdAt: '2024-12-01T16:00:00Z',
        dueDate: '2024-12-07T19:00:00Z',
    },
];
