export const motivationalQuotes = [
    "The only way to do great work is to love what you do.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The only person you are destined to become is the person you decide to be.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Believe you can and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The only person you are destined to become is the person you decide to be.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Believe you can and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The only person you are destined to become is the person you decide to be.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Believe you can and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The only person you are destined to become is the person you decide to be.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Believe you can and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The only person you are destined to become is the person you decide to be.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Believe you can and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The only person you are destined to become is the person you decide to be.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Believe you can and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The only person you are destined to become is the person you decide to be.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Believe you can and you're halfway there."
];